workspace = { members = ["libcint-sys"] }
[package]
name = "brint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.151"
libcint-sys = { path = "libcint-sys" }
